final List<Map<String, dynamic>> campgroundList = [
  {'contentId': '6734', 'name': '가야산국립공원 백운동야영장', 'location': '경북 성주군', 'type': '국립', 'firstImageUrl': null, 'lineIntro': null, 'available': 0, 'total': 0},
  {'contentId': '6822', 'name': '삼정야영장', 'location': '경북 성주군', 'type': '국립', 'firstImageUrl': null, 'lineIntro': null, 'available': 0, 'total': 0},
  {'contentId': '7067', 'name': '치인야영장', 'location': '경남 합천군', 'type': '국립', 'firstImageUrl': null, 'lineIntro': null, 'available': 0, 'total': 0},
  {'contentId': '101403', 'name': '계룡산 갑사자동차야영장', 'location': '충남 공주시', 'type': '국립', 'firstImageUrl': null, 'lineIntro': null, 'available': 0, 'total': 0},
  {'contentId': '233', 'name': '계룡산동학사자동차야영장', 'location': '충남 공주시', 'type': '국립', 'firstImageUrl': null, 'lineIntro': null, 'available': 0, 'total': 0},
  {'contentId': '6803', 'name': '백양사 가인야영장', 'location': '전남 장성군', 'type': '국립', 'firstImageUrl': null, 'lineIntro': null, 'available': 0, 'total': 0},
  {'contentId': '591', 'name': '내장산국립공원 내장야영장', 'location': '전남 장성군', 'type': '국립', 'firstImageUrl': null, 'lineIntro': null, 'available': 0, 'total': 0},
  {'contentId': '101153', 'name': '내장호야영장', 'location': '전북 정읍시', 'type': '국립', 'firstImageUrl': null, 'lineIntro': null, 'available': 0, 'total': 0},
  {'contentId': '100746', 'name': '다도해해상국립공원 구계등야영장', 'location': '전남 완도군', 'type': '국립', 'firstImageUrl': null, 'lineIntro': null, 'available': 0, 'total': 0},
  {'contentId': '2213', 'name': '염포야영장', 'location': '전남 고흥군', 'type': '국립', 'firstImageUrl': null, 'lineIntro': null, 'available': 0, 'total': 0},
  {'contentId': '3210', 'name': '팔영산야영장', 'location': '전남 고흥군', 'type': '국립', 'firstImageUrl': null, 'lineIntro': null, 'available': 0, 'total': 0},
  {'contentId': '810', 'name': '덕유대 자동차야영장', 'location': '전북 무주군', 'type': '국립', 'firstImageUrl': null, 'lineIntro': null, 'available': 0, 'total': 0},
  {'contentId': '810', 'name': '덕유대 자동차야영장2', 'location': '전북 무주군', 'type': '국립', 'firstImageUrl': null, 'lineIntro': null, 'available': 0, 'total': 0},
  {'contentId': '810', 'name': '덕유대 자동차야영장3', 'location': '전북 무주군', 'type': '국립', 'firstImageUrl': null, 'lineIntro': null, 'available': 0, 'total': 0},
  {'contentId': '8217', 'name': '도원야영장', 'location': '전남 화순군', 'type': '국립', 'firstImageUrl': null, 'lineIntro': null, 'available': 0, 'total': 0},
  {'contentId': '6808', 'name': '변산반도국립공원 고사포 야영장', 'location': '전북 부안군', 'type': '국립', 'firstImageUrl': null, 'lineIntro': null, 'available': 0, 'total': 0},
  {'contentId': '6808', 'name': '변산반도국립공원 고사포 야영장2', 'location': '전북 부안군', 'type': '국립', 'firstImageUrl': null, 'lineIntro': null, 'available': 0, 'total': 0},
  {'contentId': '101101', 'name': '북한산 사기막야영장', 'location': '경기 덕양구', 'type': '국립', 'firstImageUrl': null, 'lineIntro': null, 'available': 0, 'total': 0},
  {'contentId': '1688', 'name': '설악산국립공원 설악동자동차야영장', 'location': '강원 속초시', 'type': '국립', 'firstImageUrl': null, 'lineIntro': null, 'available': 0, 'total': 0},
  {'contentId': '1717', 'name': '소백산국립공원 남천야영장', 'location': '충북 단양군', 'type': '국립', 'firstImageUrl': null, 'lineIntro': null, 'available': 0, 'total': 0},
  {'contentId': '1718', 'name': '소백산삼가야영장', 'location': '경북 영주시', 'type': '국립', 'firstImageUrl': null, 'lineIntro': null, 'available': 0, 'total': 0},
  {'contentId': '2488', 'name': '소금강산', 'location': '강원 강릉시', 'type': '국립', 'firstImageUrl': null, 'lineIntro': null, 'available': 0, 'total': 0},
  {'contentId': '2488', 'name': '월악산국립공원 닷돈재 자동차야영장', 'location': '충북 제천시', 'type': '국립', 'firstImageUrl': null, 'lineIntro': null, 'available': 0, 'total': 0},
  {'contentId': '2488', 'name': '월악산국립공원 닷돈재 자동차야영장2', 'location': '충북 제천시', 'type': '국립', 'firstImageUrl': null, 'lineIntro': null, 'available': 0, 'total': 0},
  {'contentId': '2489', 'name': '월악산국립공원 덕주야영장', 'location': '충북 제천시', 'type': '국립', 'firstImageUrl': null, 'lineIntro': null, 'available': 0, 'total': 0},
  {'contentId': '2490', 'name': '월악산국립공원 송계자동차 야영장', 'location': '충북 제천시', 'type': '국립', 'firstImageUrl': null, 'lineIntro': null, 'available': 0, 'total': 0},
  {'contentId': '2491', 'name': '월악산국립공원 용하야영장', 'location': '충북 제천시', 'type': '국립', 'firstImageUrl': null, 'lineIntro': null, 'available': 0, 'total': 0},
  {'contentId': '100319', 'name': '하선암 카라반 야영장', 'location': '충북 단양군', 'type': '국립', 'firstImageUrl': null, 'lineIntro': null, 'available': 0, 'total': 0},
  {'contentId': '7060', 'name': '월출산국립공원 천황야영장', 'location': '전남 영암군', 'type': '국립', 'firstImageUrl': null, 'lineIntro': null, 'available': 0, 'total': 0},
  {'contentId': '2765', 'name': '주왕산국립공원 상의자동차 야영장', 'location': '경북 청송군', 'type': '국립', 'firstImageUrl': null, 'lineIntro': null, 'available': 0, 'total': 0},
  {'contentId': '590', 'name': '내원야영장', 'location': '경남 산청군', 'type': '국립', 'firstImageUrl': null, 'lineIntro': null, 'available': 0, 'total': 0},
  {'contentId': '696', 'name': '달궁자동차 야영장', 'location': '전북 남원시', 'type': '국립', 'firstImageUrl': null, 'lineIntro': null, 'available': 0, 'total': 0},
  {'contentId': '696', 'name': '달궁자동차 야영장2', 'location': '전북 남원시', 'type': '국립', 'firstImageUrl': null, 'lineIntro': null, 'available': 0, 'total': 0},
  {'contentId': '804', 'name': '덕동자동차야영장', 'location': '전북 남원시', 'type': '국립', 'firstImageUrl': null, 'lineIntro': null, 'available': 0, 'total': 0},
  {'contentId': '1266', 'name': '백무동야영장', 'location': '경남 함양군', 'type': '국립', 'firstImageUrl': null, 'lineIntro': null, 'available': 0, 'total': 0},
  {'contentId': '6806', 'name': '뱀사골 힐링야영장', 'location': '전북 남원시', 'type': '국립', 'firstImageUrl': null, 'lineIntro': null, 'available': 0, 'total': 0},
  {'contentId': '6806', 'name': '뱀사골 힐링야영장2', 'location': '전북 남원시', 'type': '국립', 'firstImageUrl': null, 'lineIntro': null, 'available': 0, 'total': 0},
  {'contentId': '1715', 'name': '소막골야영장', 'location': '경남 산청군', 'type': '국립', 'firstImageUrl': null, 'lineIntro': null, 'available': 0, 'total': 0},
  {'contentId': '7846', 'name': '학천야영장', 'location': '전북 남원시', 'type': '국립', 'firstImageUrl': null, 'lineIntro': null, 'available': 0, 'total': 0},
  {'contentId': '350', 'name': '구룡자동차야영장(치악산국립공원)', 'location': '강원 원주시', 'type': '국립', 'firstImageUrl': null, 'lineIntro': null, 'available': 0, 'total': 0},
  {'contentId': '462', 'name': '금대자동차야영장', 'location': '강원 원주시', 'type': '국립', 'firstImageUrl': null, 'lineIntro': null, 'available': 0, 'total': 0},
  {'contentId': '100551', 'name': '태백산국립공원 소도야영장', 'location': '강원 태백시', 'type': '국립', 'firstImageUrl': null, 'lineIntro': null, 'available': 0, 'total': 0},
  {'contentId': '6984', 'name': '몽산포 자동차 야영장', 'location': '충남 태안군', 'type': '국립', 'firstImageUrl': null, 'lineIntro': null, 'available': 0, 'total': 0},
  {'contentId': '3394', 'name': '학암포 오토 캠핑장', 'location': '충남 태안군', 'type': '국립', 'firstImageUrl': null, 'lineIntro': null, 'available': 0, 'total': 0},
  {'contentId': '100338', 'name': '팔공산국립공원 갓바위야영장', 'location': '경북 경산시', 'type': '국립', 'firstImageUrl': null, 'lineIntro': null, 'available': 0, 'total': 0},
  {'contentId': '6973', 'name': '팔공산국립공원 도학 야영장', 'location': '대구 동구', 'type': '국립', 'firstImageUrl': null, 'lineIntro': null, 'available': 0, 'total': 0},
  {'contentId': '101772', 'name': '덕신야영장', 'location': '경남 남해군', 'type': '국립', 'firstImageUrl': null, 'lineIntro': null, 'available': 0, 'total': 0},
  {'contentId': '3389', 'name': '학동자동차 야영장', 'location': '경남 거제시', 'type': '국립', 'firstImageUrl': null, 'lineIntro': null, 'available': 0, 'total': 0},
];
