// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAG9M0MrIEX0S7QKd1sF-Gmz8a-6ncePRw',
    appId: '1:986445583170:android:2516407d2e4edad65c6edb',
    messagingSenderId: '986445583170',
    projectId: 'camping-8ae8b',
    storageBucket: 'camping-8ae8b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPdQjzNT63NWmbsYGulLkFr3s573fpCU4',
    appId: '1:986445583170:ios:bfb878ea787d1e8b5c6edb',
    messagingSenderId: '986445583170',
    projectId: 'camping-8ae8b',
    storageBucket: 'camping-8ae8b.firebasestorage.app',
    iosBundleId: 'com.example.camping',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPjbKm9j5hBqNPI0aDIp2V5Tzuuvfyho8',
    appId: '1:986445583170:web:b813ccbe1dc7a4d85c6edb',
    messagingSenderId: '986445583170',
    projectId: 'camping-8ae8b',
    authDomain: 'camping-8ae8b.firebaseapp.com',
    storageBucket: 'camping-8ae8b.firebasestorage.app',
  );

}